version: "3"

services:
  monies:
    image: node:10.7
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: >
      bash -c "npm i && ./node_modules/.bin/nodemon ./src/index.js"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass

networks:
  monies:
